import { EmailAccount, EmailMessage } from '../types/index.ts';

export function generateSampleEmailsForAccount(account: EmailAccount): EmailMessage[] {
  const now = new Date();
  
  const samples = [
    {
      sender: 'offerte@zalando.it',
      senderName: 'Zalando Privé',
      subject: '🔥 Sconti fino al -70% su abbigliamento e scarpe solo per oggi!',
      snippet: 'Scopri la selezione esclusiva di capi di marca a prezzi mai visti prima. Offerta a tempo limitato.',
      daysAgo: 1,
      sizeKb: 1420,
      folder: 'promotions' as const,
      isRead: false,
      isStarred: false,
      isReceipt: false,
    },
    {
      sender: 'newsletter@groupon.it',
      senderName: 'Groupon Offerte',
      subject: 'Coupon sconto 20% su ristoranti, spa ed esperienze vicino a te',
      snippet: 'Usa il codice promozionale MAGGIO20 per risparmiare subito su migliaia di offerte locali.',
      daysAgo: 3,
      sizeKb: 890,
      folder: 'promotions' as const,
      isRead: false,
      isStarred: false,
      isReceipt: false,
    },
    {
      sender: 'promozioni@unieuro.it',
      senderName: 'Unieuro Online',
      subject: 'Il Fuoritutto continua: Smart TV e Smartphone in super sconto',
      snippet: 'Spedizione gratuita per ordini superiori a 49€. Sfoglia il volantino digitale.',
      daysAgo: 5,
      sizeKb: 2100,
      folder: 'promotions' as const,
      isRead: true,
      isStarred: false,
      isReceipt: false,
    },
    {
      sender: 'updates@linkedin.com',
      senderName: 'LinkedIn Notifiche',
      subject: 'Hai 8 nuove visualizzazioni del profilo questa settimana',
      snippet: 'Vedi chi ha visitato il tuo profilo e scopri le nuove offerte di lavoro consigliate per te.',
      daysAgo: 7,
      sizeKb: 340,
      folder: 'social' as const,
      isRead: true,
      isStarred: false,
      isReceipt: false,
    },
    {
      sender: 'marketing@booking.com',
      senderName: 'Booking.com Deals',
      subject: 'La tua prossima vacanza ti aspetta: Offerte lampo estate 2026',
      snippet: 'Risparmia il 15% o più sui soggiorni prenotati entro la fine del mese.',
      daysAgo: 12,
      sizeKb: 1120,
      folder: 'promotions' as const,
      isRead: true,
      isStarred: false,
      isReceipt: false,
    },
    {
      sender: 'noreply@newsletter.ebay.it',
      senderName: 'eBay Italia',
      subject: 'Ultimi giorni: Buono sconto 10€ per la tua spesa online',
      snippet: 'Inserisci il codice nel carrello prima del checkout. Valido su milioni di articoli.',
      daysAgo: 18,
      sizeKb: 780,
      folder: 'promotions' as const,
      isRead: true,
      isStarred: false,
      isReceipt: false,
    },
    {
      sender: 'info@news.mediaworld.it',
      senderName: 'MediaWorld Club',
      subject: 'Volantino Tech Mania: rate a tasso zero su tutta la tecnologia',
      snippet: 'Scopri i nuovi arrivi Apple, Samsung e Sony a condizioni imperdibili.',
      daysAgo: 24,
      sizeKb: 1890,
      folder: 'promotions' as const,
      isRead: true,
      isStarred: false,
      isReceipt: false,
    },
    {
      sender: 'offerte@shein.com',
      senderName: 'SHEIN Daily',
      subject: 'Super Saldi di Metà Stagione: tutto da 1.99€!',
      snippet: 'Oltre 10.000 nuovi arrivi a prezzi stracciati. Punti doppi per ogni acquisto.',
      daysAgo: 35,
      sizeKb: 2450,
      folder: 'promotions' as const,
      isRead: true,
      isStarred: false,
      isReceipt: false,
    },
    {
      sender: 'conferma-ordine@amazon.it',
      senderName: 'Amazon.it Ordini',
      subject: 'Conferma del tuo ordine n. 408-9821445-1234567 (Ricevuta)',
      snippet: 'Grazie per il tuo ordine! La spedizione è prevista per domani con corriere espresso.',
      daysAgo: 4,
      sizeKb: 510,
      folder: 'inbox' as const,
      isRead: true,
      isStarred: true,
      isReceipt: true, // PROTETTA DA REGOLE
    },
    {
      sender: 'fatture@servizioclienti.enel.it',
      senderName: 'Enel Energia',
      subject: 'Emissione Fattura n. 889210/2026 - Documento Contabile',
      snippet: 'In allegato la fattura relativa ai consumi dell\'ultimo bimestre. Importo: 68,40€.',
      daysAgo: 15,
      sizeKb: 820,
      folder: 'inbox' as const,
      isRead: true,
      isStarred: true,
      isReceipt: true, // PROTETTA DA REGOLE
    },
    {
      sender: 'newsletter@tripadvisor.it',
      senderName: 'Tripadvisor Viaggi',
      subject: 'I migliori 10 ristoranti panoramici da provare nel weekend',
      snippet: 'Scopri le recensioni della community e prenota un tavolo con TheFork.',
      daysAgo: 45,
      sizeKb: 1300,
      folder: 'promotions' as const,
      isRead: true,
      isStarred: false,
      isReceipt: false,
    },
    {
      sender: 'spam-service@promo-direct-hub.xyz',
      senderName: 'Vincite & Premi Online',
      subject: 'URGENTE: Ritira il tuo buono carburante Eni da 500€',
      snippet: 'Sei stato selezionato tra i finalisti del concorso a premi dell\'anno.',
      daysAgo: 50,
      sizeKb: 620,
      folder: 'spam' as const,
      isRead: true,
      isStarred: false,
      isReceipt: false,
    }
  ];

  return samples.map((item, idx) => {
    const itemDate = new Date(now.getTime() - item.daysAgo * 24 * 60 * 60 * 1000);
    return {
      id: `mail-${account.id}-${idx}-${Date.now()}`,
      accountId: account.id,
      accountEmail: account.email,
      sender: item.sender,
      senderName: item.senderName,
      subject: item.subject,
      snippet: item.snippet,
      date: itemDate.toISOString(),
      sizeKb: item.sizeKb,
      folder: item.folder,
      isRead: item.isRead,
      isStarred: item.isStarred,
      isReceipt: item.isReceipt,
      status: 'inbox' as const,
    };
  });
}
